name: check-and-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest stable release tag
        id: get_release
        run: |
          latest=$(curl -s https://api.github.com/repos/awawa-dev/HyperHDR/releases | jq -r '[.[] | select(.prerelease == false)][0].tag_name')
          echo "latest_version=$latest" >> "$GITHUB_ENV"

      - name: Check if Docker image already exists
        id: docker_tag_check
        run: |
          tag_exists=$(curl -s https://hub.docker.com/v2/repositories/obaida/hyperhdr-aarch64/tags/${{ env.latest_version }}) 
          if echo "$tag_exists" | jq -e '.name' >/dev/null; then
            echo "Image already exists. Skipping build."
            echo "skip_build=true" >> "$GITHUB_ENV"
          else
            echo "Image does not exist. Proceeding to build."
            echo "skip_build=false" >> "$GITHUB_ENV"
          fi

      - name: Clone HyperHDR source
        if: env.skip_build == 'false'
        run: |
          git clone --branch ${{ env.latest_version }} --recurse-submodules https://github.com/awawa-dev/HyperHDR.git addon-hyperhdr/hyperhdr-source

      - name: Set up QEMU
        if: env.skip_build == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.skip_build == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.skip_build == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push multi-arch Docker image with cache
        if: env.skip_build == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ./addon-hyperhdr
          file: ./addon-hyperhdr/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            obaida/hyperhdr-aarch64:${{ env.latest_version }}
            obaida/hyperhdr-aarch64:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
