# ----------------------
# Updated GitHub Actions Workflow
# ----------------------

name: check-and-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  IMAGE_NAME: obaida/hyperhdr

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            base_image: ubuntu:22.04
          - arch: arm64
            platform: linux/arm64
            base_image: arm64v8/ubuntu:22.04
          - arch: armv7
            platform: linux/arm/v7
            base_image: arm32v7/ubuntu:22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest stable release tag
        id: get_release
        run: |
          latest=$(curl -s https://api.github.com/repos/awawa-dev/HyperHDR/releases | jq -r '[.[] | select(.prerelease == false)][0].tag_name')
          echo "latest_version=$latest" >> "$GITHUB_ENV"

      - name: Check if Docker image already exists
        id: docker_tag_check
        run: |
          tag_exists=$(curl -s https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}-${{ matrix.arch }}/tags/${{ env.latest_version }})
          if echo "$tag_exists" | jq -e '.name' >/dev/null; then
            echo "skip_build=true" >> "$GITHUB_ENV"
          else
            echo "skip_build=false" >> "$GITHUB_ENV"
          fi

      - name: Clone HyperHDR source
        if: env.skip_build == 'false'
        run: |
          git clone --branch ${{ env.latest_version }} --recurse-submodules https://github.com/awawa-dev/HyperHDR.git addon-hyperhdr/hyperhdr-source

      - name: Set up QEMU
        if: env.skip_build == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.skip_build == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.skip_build == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push image for ${{ matrix.arch }}
        if: env.skip_build == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ./addon-hyperhdr
          file: ./addon-hyperhdr/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
          tags: |
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ env.latest_version }}
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build summary
        if: env.skip_build == 'false'
        run: echo "✅ HyperHDR ${{ env.latest_version }} built and pushed for ${{ matrix.arch }}"

      - name: Skip summary
        if: env.skip_build == 'true'
        run: echo "ℹ️ No new stable release. Build skipped for ${{ matrix.arch }}"
