name: Build & Push HyperHDR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Vérifie chaque jour à 2h du matin

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier la dernière version stable de HyperHDR
        id: check_version
        run: |
          latest_version=$(curl --silent "https://api.github.com/repos/awawa-dev/HyperHDR/releases/latest" | jq -r .tag_name)
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Vérifier si une nouvelle version doit être construite
        id: should_build
        run: |
          docker_tags=$(curl --silent "https://hub.docker.com/v2/repositories/obaida/hyperhdr/tags/")
          if echo "$docker_tags" | grep -q "\"name\": \"$latest_version\""; then
            echo "build_needed=false" >> $GITHUB_ENV
          else
            echo "build_needed=true" >> $GITHUB_ENV
          fi

      - name: Cloner le dépôt HyperHDR
        if: env.build_needed == 'true'
        run: |
          git clone --branch ${{ env.latest_version }} --recurse-submodules https://github.com/awawa-dev/HyperHDR.git ./addon-hyperhdr/hyperhdr-source

      - name: Configurer QEMU
        if: env.build_needed == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Configurer Docker Buildx
        if: env.build_needed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Se connecter à Docker Hub
        if: env.build_needed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire et pousser l'image Docker multi-architecture
        if: env.build_needed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./addon-hyperhdr
          file: ./addon-hyperhdr/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: obaida/hyperhdr:${{ env.latest_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
